schema_version: 1

context:
  name: typst-py
  version: "0.14.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/typst/typst-${{ version }}.tar.gz
  sha256: 53a7ee0825c127c100023685eeb8fb911226d7ad9ae861a370c11bb0f5c160cc

build:
  number: 1
  # only build for the minimal python version
  skip: is_abi3 and not is_python_min
  python:
    version_independent: true
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      # Remove this wrapper once https://github.com/conda-forge/rust-activation-feedstock/pull/79 is merged
      - if: unix
        then:
          - mkdir -p ${BUILD_PREFIX}/bin
          - cp ${RECIPE_DIR}/cargo-auditable-wrapper.sh ${BUILD_PREFIX}/bin/cargo-auditable-wrapper
          - export CARGO="cargo-auditable-wrapper"
        else:
          - copy %RECIPE_DIR%\cargo-auditable-wrapper.bat %BUILD_PREFIX%\Library\bin\cargo-auditable-wrapper.bat
          - set "CARGO=cargo-auditable-wrapper.bat"
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - make
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
    - if: is_abi3
      then: python-abi3

  run:
    - python

tests:
  - python:
      imports:
        - typst
      pip_check: true
      python_version:
        - "*"
        - ${{ python_min }}
  - if: is_abi3
    then:
      script:
        - if: win
          then: abi3audit %PREFIX%/Lib/site-packages/typst/_typst.pyd -s -v --assume-minimum-abi3 ${{ python_min }}
          else:
            - export SP_DIR=$(python -c "import site; print(site.getsitepackages()[0])")
            - abi3audit $SP_DIR/typst/_typst.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
      requirements:
        run:
          - abi3audit


about:
  summary: Python binding to typst
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/messense/typst-py

extra:
  recipe-maintainers:
    - freundTech
    - pavelzw
